# Generated by Django 5.1.5 on 2025-01-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='karyaSeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul_Karya', models.CharField(max_length=128)),
                ('Nama_pembuat', models.CharField(max_length=64)),
                ('deskripsi', models.CharField(max_length=258)),
                ('harga', models.IntegerField()),
            ],
        ),
    ]
